function menu_goto( menuform )
{
  // Generated by thesitewizard Navigation Menu Wizard 2.3.6
  // Visit http://www.thesitewizard.com/ to get your own
  // customized navigation menu FREE!
  var baseurl = 'http://www.givemepro.com/' ;
  selecteditem = menuform.url.selectedIndex ;
  newurl = menuform.url.options[ selecteditem ].value ;
  if (newurl.length != 0) {
    location.href = baseurl + newurl ;
  }
}
document.writeln( '<form action="chgoto" method="get">' );
document.writeln( '<select name="url" onchange="menu_goto(this.form)">' );
document.writeln( '<option value="">google</option>' );
document.writeln( '<option value="">facebook</option>' );
document.writeln( '<option value="">yahoo</option>' );
document.writeln( '</select>' );
document.writeln( '</form>' );


